services:
  db:
    image: postgres:16
    container_name: culinary_db
    restart: always
    environment:
      POSTGRES_DB: culinary_book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - culinary_pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d culinary_book"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Backend
    container_name: culinary_backend
    restart: always
    env_file:
      - ./Backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
    container_name: culinary_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  culinary_pgdata: